name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ви можете використовувати іншу гілку, якщо потрібно
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонування репозиторію
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Налаштування Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Виберіть відповідну версію Python

    # 3. Встановлення залежностей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запуск тестів
    - name: Run tests
      run: |
        python -m unittest discover

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 1. Клонування репозиторію
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Встановлення Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Логін в DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Створення Docker образу
    - name: Build Docker image
      run: |
        docker build -t yourusername/yourimage:latest .

    # 5. Публікація Docker образу на DockerHub
    - name: Push Docker image
      run: |
        docker push yourusername/yourimage:latest
